#Faris alsubaie
# 10/29/2020

#This dataset contains a list of video games with sales greater than 100,000 copies. 
#It was generated by a scrape of vgchartz.com.

#%%
import math
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt





#%% load packages
vgsales = pd.read_csv("data/vgsales.csv")

# %%
vgsales['Name']

#%%

vgsales_region = vgsales[['Name', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales']]
    [(vgsales.Publisher == "Nintendo", "Microsoft Game Studios", "Sony Computer Entertainment")]

# %%
vgsales.describe()

# %%
games_genre = vgsales.groupby('Genre')['NA_Sales', 'EU_Sales', 'JP_Sales']
#%% Games sales by genre
games_genre




# %%
vgsales.groupby("Year")["Global_Sales"].sum().plot(kind="line", grid=True, legend=True)
# %%
